name: Build and Publish BOM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to Gitea Maven
      if: github.ref == 'refs/heads/main'
      run: ./gradlew publishMavenPublicationToGiteaRepository
      env:
        GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
