name: Build and Publish BOM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # JDK 21 already in custom runner image - no setup needed!

    - name: Build with Gradle
      run: ./gradlew build --no-daemon --build-cache

    - name: Publish to Gitea Maven
      if: github.ref == 'refs/heads/main'
      run: ./gradlew publishMavenPublicationToGiteaRepository -Pgitea.token=$MAVEN_PUBLISH_TOKEN
      env:
        MAVEN_PUBLISH_TOKEN: ${{ secrets.MAVEN_PUBLISH_TOKEN }}
